services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: turnip
      POSTGRES_PASSWORD: turnips
      POSTGRES_DB: turnip_exchanger
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: