"""empty message

Revision ID: f5806ecf0da5
Revises: 
Create Date: 2026-04-01 18:03:07.725833

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f5806ecf0da5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enum changes not detected automatically by Alembic
    op.execute("ALTER TYPE queuestatus RENAME VALUE 'open' TO 'active'")
    op.execute("ALTER TYPE oauthprovider ADD VALUE IF NOT EXISTS 'email'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friendshipstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship')
    )
    op.create_table('islands',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('island_name', sa.String(length=128), nullable=False),
    sa.Column('host_name', sa.String(length=64), nullable=False),
    sa.Column('hemisphere', sa.Enum('north', 'south', name='hemisphere'), nullable=False),
    sa.Column('fruit', sa.Enum('apple', 'pear', 'cherry', 'peach', 'orange', name='fruit'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strikes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('no_confirmation', 'kicked_by_host', name='strikereason'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_messages',
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dodo_codes')
    op.drop_table('messages')
    op.drop_table('turnip_prices')
    op.add_column('bans', sa.Column('ban_from', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('bans', 'banned_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('chats', 'updated_at')
    op.drop_column('queue_users', 'position')
    op.add_column('queues', sa.Column('island_id', sa.UUID(), nullable=False))
    sa.Enum('turnips', 'objects', name='queuecategory').create(op.get_bind())
    op.add_column('queues', sa.Column('category', sa.Enum('turnips', 'objects', name='queuecategory'), nullable=False))
    op.add_column('queues', sa.Column('dodo_code', sa.String(length=5), nullable=False))
    op.add_column('queues', sa.Column('limit', sa.Integer(), nullable=False))
    op.add_column('queues', sa.Column('visit_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('queues', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('queues', 'turnip_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('queues_host_id_fkey'), 'queues', type_='foreignkey')
    op.create_foreign_key(None, 'queues', 'islands', ['island_id'], ['id'])
    op.drop_column('queues', 'updated_at')
    op.drop_column('queues', 'max_visitors')
    op.drop_column('queues', 'host_id')
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'oauth_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'island_name')
    op.add_column('visits', sa.Column('island_id', sa.UUID(), nullable=False))
    op.add_column('visits', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('visits', sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visits', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('visits_host_id_fkey'), 'visits', type_='foreignkey')
    op.drop_constraint(op.f('visits_visitor_id_fkey'), 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'visits', 'islands', ['island_id'], ['id'])
    op.drop_column('visits', 'updated_at')
    op.drop_column('visits', 'visitor_id')
    op.drop_column('visits', 'started_at')
    op.drop_column('visits', 'host_id')
    op.drop_column('visits', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Enum changes (note: PostgreSQL doesn't support removing enum values, only renaming)
    op.execute("ALTER TYPE queuestatus RENAME VALUE 'active' TO 'open'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('visits', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('visits', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('visits_visitor_id_fkey'), 'visits', 'users', ['visitor_id'], ['id'])
    op.create_foreign_key(op.f('visits_host_id_fkey'), 'visits', 'users', ['host_id'], ['id'])
    op.drop_column('visits', 'left_at')
    op.drop_column('visits', 'entered_at')
    op.drop_column('visits', 'user_id')
    op.drop_column('visits', 'island_id')
    op.add_column('users', sa.Column('island_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.alter_column('users', 'oauth_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'password_hash')
    op.add_column('queues', sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('max_visitors', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.create_foreign_key(op.f('queues_host_id_fkey'), 'queues', 'users', ['host_id'], ['id'])
    op.alter_column('queues', 'turnip_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('queues', 'closed_at')
    op.drop_column('queues', 'visit_ends_at')
    op.drop_column('queues', 'limit')
    op.drop_column('queues', 'dodo_code')
    op.drop_column('queues', 'category')
    sa.Enum(name='queuecategory').drop(op.get_bind())
    op.drop_column('queues', 'island_id')
    op.add_column('queue_users', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('chats', 'last_message_at')
    op.alter_column('bans', 'banned_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bans', 'ban_from')
    op.create_table('turnip_prices',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buy_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sell_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot', postgresql.ENUM('monday_am', 'monday_pm', 'tuesday_am', 'tuesday_pm', 'wednesday_am', 'wednesday_pm', 'thursday_am', 'thursday_pm', 'friday_am', 'friday_pm', 'saturday_am', 'saturday_pm', name='priceslot'), autoincrement=False, nullable=False),
    sa.Column('week_of', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('turnip_prices_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('turnip_prices_pkey'))
    )
    op.create_table('messages',
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('messages_chat_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_table('dodo_codes',
    sa.Column('queue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('dodo_codes_queue_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dodo_codes_pkey')),
    sa.UniqueConstraint('queue_id', name=op.f('dodo_codes_queue_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('queue_messages')
    op.drop_table('private_messages')
    op.drop_table('strikes')
    op.drop_table('islands')
    op.drop_table('friendships')
    # ### end Alembic commands ###
